#!/bin/bash
#软件安装配置文件

# 需使用npm安装jsonlint

echo "检查npm是否安装"
if [[ ! $(which npm) ]]; then
	echo "请先安装npm"
	exit 1
else
	echo "检查jsonlint是否安装"

	if [[ ! $(which jsonlint) ]]; then
		sudo npm install jsonlint -g
	fi
fi

echo "配置解析JSON文件的命令'jq'"
if [[ ! $(which jq) ]]; then
	echo "安装'jq'程序"
	sudo apt-get isntall jq
fi

echo "检查$HOME/bin文件夹中依赖的程序是否存在"
LOCAL_PROG=(blue yellow)

for prog in "${LOCAL_PROG[@]}"; do
	if [[ ! -f $HOME/bin/$prog ]]; then
		echo "不存在本地程序$HOME/$prog"
	fi
done

echo -e "\n配置成功!"
